version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nodeapp:latest .   
      - docker tag nodeapp:latest 843982302747.dkr.ecr.us-west-2.amazonaws.com/c1as-linux:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 843982302747.dkr.ecr.us-west-2.amazonaws.com/c1as-linux:latest
      - printf '[{"name":"c1as-docker","imageUri":"843982302747.dkr.ecr.us-west-2.amazonaws.com/c1as-linux:latest"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

