version: 0.2


phases:
  build:
    commands:
      - ls
      - docker
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nodeapp:latest .   
      - docker tag nodeapp:latest 843982302747.dkr.ecr.us-west-2.amazonaws.com/c1as-linux:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 843982302747.dkr.ecr.us-west-2.amazonaws.com/c1as-linux:latest
artifacts:
    files: imagedefinitions.json

